spring:
  application:
    name: gateway
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: ${ZOOKEEPER_HOST:localhost}:2181
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
