loadbalancer:
  client:
    name: order-service
spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: ${ZOOKEEPER_HOST:localhost}:2181
  application:
    name: payment-service
  kafka:
    consumer:
      bootstrap-servers:
        - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: payment
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers:
        - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
