spring:
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 4000
        max-interval: 60000
        multiplier: 2
  application:
    name: book-service
#  kafka:
#    consumer:
#      bootstrap-servers:
#        - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#      group-id: book
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

